# Generated by Django 4.2.5 on 2023-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('item_name', models.CharField(max_length=70)),
                ('item_code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
