# Generated by Django 4.2.5 on 2023-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='datetime',
            field=models.DateField(),
        ),
    ]
