# Generated by Django 4.2.2 on 2023-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=70)),
                ('mobile_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
