# Generated by Django 4.2.2 on 2023-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchase_mstr_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_mstr',
            name='date',
            field=models.DateField(),
        ),
    ]
