# Generated by Django 4.2.2 on 2023-09-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_purchase_mstr_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_details',
            old_name='purchase_mstr',
            new_name='purchase_id',
        ),
    ]
