# Generated by Django 4.2.2 on 2023-09-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_temp_table_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_table',
            name='purchase_id',
        ),
        migrations.RemoveField(
            model_name='temp_table',
            name='status',
        ),
    ]
