# Generated by Django 4.2.2 on 2023-09-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_temp_table_purchase_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_details',
            name='purchase_id',
        ),
        migrations.RemoveField(
            model_name='temp_table',
            name='total_amount',
        ),
    ]
