# Generated by Django 4.2.2 on 2023-09-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_purchase_details_purchase_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_details',
            name='purchase_mstr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.purchase_mstr'),
        ),
    ]
