# Generated by Django 4.2.2 on 2023-09-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_purchase_details_purchase_mstr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='purchase_mstr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase_mstr'),
        ),
    ]
