# Generated by Django 4.2.2 on 2023-09-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_purchase_details_purchase_mstr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_details',
            old_name='purchase_mstr_id',
            new_name='purchase_mstr',
        ),
    ]
