# Generated by Django 4.2.2 on 2023-09-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_purchase_mstr_id_purchase_details_purchase_mstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_details',
            name='purchase_mstr',
        ),
    ]
