# Generated by Django 4.2.2 on 2023-09-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_purchase_details_purchase_mstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Purchase_Mstr',
            new_name='Purchase_Mstrs',
        ),
        migrations.DeleteModel(
            name='Purchase_Details',
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='Purchase_Mstrs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase_mstrs'),
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
