# Generated by Django 4.2.2 on 2023-09-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_purchase_detail_rename_purchase_mstr_purchase_mstrs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_Detail',
            new_name='Purchase_Details',
        ),
        migrations.RenameModel(
            old_name='Purchase_Mstrs',
            new_name='Purchase_Mstr',
        ),
    ]
