# Generated by Django 4.2.2 on 2023-09-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_purchase_detail_purchase_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_details',
            old_name='Purchase_Mstrs_id',
            new_name='purchase_mstr',
        ),
    ]
