# Generated by Django 4.2.2 on 2023-09-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_purchase_mstrs_id_purchase_details_purchase_mstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_details',
            name='status',
        ),
    ]
